Integration specs
SFarida/rails_blog_app pull request #8
Opened 2023-06-21 22:55 UTC by SFarida

#### n+1
- Make sure that the N+1 problem is solved when fetching all posts and their comments for a user.
    - Do not use the bullet gem in this exercise - instead analyze the logs as showed in this [article](https://dev.to/junko911/rails-n-1-queries-and-eager-loading-10eh)
    - **In your PR description include the screenshots of your app's logs before and after the fix**
    - This is the corresponding wireframe view: ![blog all user posts](../images/blog_user_all_posts.png)

#### Integration specs
- Use Capybara to write integration tests for each view in your project.
- Think on the flow of things and group the tests of page in a way that makes sense. For example, one test would check for the things in the page and another test for clicking links on it.

- User index page:
  - I can see the username of all other users.
  - I can see the profile picture for each user.
  - I can see the number of posts each user has written.
  - When I click on a user, I am redirected to that user's show page.

- user show page:
  - I can see the user's profile picture.
  - I can see the user's username.
  - I can see the number of posts the user has written.
  - I can see the user's bio.
  - I can see the user's first 3 posts.
  - I can see a button that lets me view all of a user's posts.
  - When I click a user's post, it redirects me to that post's show page.
  - When I click to see all posts, it redirects me to the user's post's index page.

- User post index page:
  - I can see the user's profile picture.
  - I can see the user's username.
  - I can see the number of posts the user has written.
  - I can see a post's title.
  - I can see some of the post's body.
  - I can see the first comments on a post.
  - I can see how many comments a post has.
  - I can see how many likes a post has.
  - I can see a section for pagination if there are more posts than fit on the view.
  - When I click on a post, it redirects me to that post's show page.

- Post show page:
  - I can see the post's title.
  - I can see who wrote the post.
  - I can see how many comments it has.
  - I can see how many likes it has.
  - I can see the post body.
  - I can see the username of each commentor.
  - I can see the comment each commentor left.

2023-06-22 00:58 UTC, Reem-lab requested changes
# Hi @SFarida and @jaimevillegas, 👋🏻👋🏻

Great job so far! 🚀✨💯🔥
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/LuRH8UGQTPEx2lafrD/giphy-downsized-medium.gif"/>

## Highlights
- Followed Gitflow 💯🚀
- Great job working on the fuctionality for the tests⭐
- No linters error 💯🚀✨
- All tests passed ⭐🔥
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-22 00:58 UTC, Reem-lab commented on spec/post_index_spec.rb
> +  end
- [ ] Great job working on the tests but I think you missed some tests so I think it would be great if you add them as well 🤩🙏🏻🚀


- Tests that asserts you can see the first comments on a post.
- Tests that asserts you can see a section for pagination if there are more posts than fit on the view.

2023-06-22 00:58 UTC, Reem-lab commented on spec/user_index_spec.rb
> +  end
- [ ] Great job working on the tests but I think you missed some tests so I think it would be great if you add them as well 🤩🙏🏻🚀

- Tests that redirects to the user's show page when you click on a user. 🚀⭐

2023-06-22 00:58 UTC, Reem-lab commented on spec/user_show_spec.rb
> +  end
- [ ] Great job working on the tests but I think you missed some tests so I think it would be great if you add them as well 🤩🙏🏻🚀

- Tests that redirects to the post's show page when you click on a user's post. ⭐🚀

2023-06-22 00:58 UTC, Reem-lab commented on app/controllers/posts_controller.rb
> +    @post = Post.includes(:author, :comments, :likes).find(params[:id])
- [ ] I think it would be great if you add this line in index method above since we want to solve the n+1 problem when fetching all posts and their comments for a user as shown in the wireframe 🚀⭐ so kindly fix it 🔥💪🏻

2023-06-23 23:28 UTC, bienvenuushindi approved these changes
# STATUS: APPROVED 🟢 

## Hi @SFarida   👋, 

Well done implementing the requested changes 👏
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/lJNoBCvQYp7nq/giphy.gif"/>

### Highlights 🎯 
:+1: No linter errors✔️
:+1: Good PR title

### Optional Suggestions



**_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-24 18:38 UTC, merged